import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./componenets/SessionWrapper";
import LoginScreen from "./componenets/LoginScreen";
import { getServerSession } from "next-auth";
import { authOptions } from "../lib/auth";
import ClientEffects from "./componenets/ClientEffects";
import BackgroundEffects from "./componenets/BackgroundEffects";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
        style={{
          background: "#000",
          margin: 0,
          padding: 0,
          overflow: "hidden",
          cursor: "none",
        }}
      >
        <BackgroundEffects />
        <ClientEffects />

        {/* ── Page ─────────────────────────────────────── */}
        <SessionWrapper>
          <main
            style={{
              display: "flex",
              minHeight: "100vh",
              alignItems: "center",
              justifyContent: "center",
              background: "#050505",
              fontFamily: "var(--font-outfit), apple-system, sans-serif",
              position: "relative",
              zIndex: 10,
              overflow: "hidden",
            }}
          >
            {!session ? <LoginScreen /> : children}
          </main>
        </SessionWrapper>


      </body>
    </html>
  );
}