import type { Metadata } from "next";
import { Outfit, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignUp } from "@clerk/nextjs";
import ClientEffects from "./componenets/ClientEffects";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${cormorant.variable} antialiased`}
        style={{
          background: "#0d0800",
          margin: 0,
          padding: 0,
          overflow: "hidden",
          cursor: "none",
        }}
      >
        {/* ── Single ambient wallpaper glow ─────────────── */}
        <div
          style={{
            position: "fixed",
            inset: 0,
            background: `
              radial-gradient(ellipse 80% 60% at 20% 50%, rgba(200,90,10,0.13) 0%, transparent 60%),
              radial-gradient(ellipse 60% 70% at 80% 40%, rgba(255,160,40,0.08) 0%, transparent 55%),
              radial-gradient(ellipse 100% 80% at 50% 100%, rgba(160,50,0,0.08) 0%, transparent 50%)
            `,
            pointerEvents: "none",
            zIndex: 0,
          }}
        />

        {/* ── Interactive cursor + spotlight (client) ───── */}
        <ClientEffects />

        {/* ── Page ─────────────────────────────────────── */}
        <ClerkProvider>
          <main
            style={{
              display: "flex",
              minHeight: "100vh",
              alignItems: "center",
              justifyContent: "center",
              background: "transparent",
              fontFamily: "var(--font-outfit), apple-system, sans-serif",
              position: "relative",
              zIndex: 10,
              overflow: "hidden",
            }}
          >
            <SignedOut>
              <SignUp />
            </SignedOut>
            <SignedIn>{children}</SignedIn>
          </main>
        </ClerkProvider>
      </body>
    </html>
  );
}