import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignUp } from "@clerk/nextjs";
import ClientEffects from "./componenets/ClientEffects";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
        style={{
          background: "#000",
          margin: 0,
          padding: 0,
          overflow: "hidden",
          cursor: "none",
        }}
      >
        {/* ── Ambient orbs ─────────────────────────────── */}

        {/* Orb 1 — purple, top-left */}
        <div
          style={{
            position: "fixed",
            width: 350,
            height: 350,
            borderRadius: "50%",
            top: "5%",
            left: "5%",
            background:
              "radial-gradient(circle, rgba(110,70,240,0.09), transparent 70%)",
            filter: "blur(70px)",
            pointerEvents: "none",
            zIndex: 0,
            animation: "drift1 11s ease-in-out infinite",
          }}
        />

        {/* Orb 2 — white, bottom-right */}
        <div
          style={{
            position: "fixed",
            width: 250,
            height: 250,
            borderRadius: "50%",
            bottom: "10%",
            right: "10%",
            background:
              "radial-gradient(circle, rgba(255,255,255,0.04), transparent 70%)",
            filter: "blur(70px)",
            pointerEvents: "none",
            zIndex: 0,
            animation: "drift2 14s ease-in-out infinite",
          }}
        />

        {/* Orb 3 — blue, bottom-left */}
        <div
          style={{
            position: "fixed",
            width: 180,
            height: 180,
            borderRadius: "50%",
            bottom: "25%",
            left: "8%",
            background:
              "radial-gradient(circle, rgba(60,140,255,0.07), transparent 70%)",
            filter: "blur(70px)",
            pointerEvents: "none",
            zIndex: 0,
            animation: "drift1 18s ease-in-out infinite reverse",
          }}
        />

        {/* ── Hairline rules ────────────────────────────── */}
        <div
          style={{
            position: "fixed",
            left: 0,
            right: 0,
            top: "28%",
            height: 1,
            background:
              "linear-gradient(90deg, transparent, rgba(255,255,255,0.045) 20%, rgba(255,255,255,0.045) 80%, transparent)",
            pointerEvents: "none",
            zIndex: 1,
          }}
        />
        <div
          style={{
            position: "fixed",
            left: 0,
            right: 0,
            bottom: "28%",
            height: 1,
            background:
              "linear-gradient(90deg, transparent, rgba(255,255,255,0.045) 20%, rgba(255,255,255,0.045) 80%, transparent)",
            pointerEvents: "none",
            zIndex: 1,
          }}
        />

        {/* ── Film grain overlay ────────────────────────── */}
        <div
          style={{
            position: "fixed",
            inset: 0,
            zIndex: 2,
            pointerEvents: "none",
            opacity: 0.04,
            backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E")`,
            backgroundSize: "180px 180px",
          }}
        />

        {/* ── Interactive cursor + spotlight (client) ───── */}
        <ClientEffects />

        {/* ── Page ─────────────────────────────────────── */}
        <ClerkProvider>
          <main
            style={{
              display: "flex",
              minHeight: "100vh",
              alignItems: "center",
              justifyContent: "center",
              background: "#050505",
              fontFamily: "var(--font-outfit), apple-system, sans-serif",
              position: "relative",
              zIndex: 10,
              overflow: "hidden",
            }}
          >
            <SignedOut>
              <SignUp
                afterSignUpUrl="/"
                appearance={{
                  layout: {
                    socialButtonsVariant: "iconButton",
                    logoPlacement: "inside",
                  },
                  variables: {
                    colorBackground:     "#0c0c0e",
                    colorInputBackground: "rgba(255,255,255,0.04)",
                    colorInputText:      "rgba(255,255,255,0.85)",
                    colorText:           "rgba(255,255,255,0.85)",
                    colorTextSecondary:  "rgba(255,255,255,0.35)",
                    colorPrimary:        "#ffffff",
                    colorTextOnPrimaryBackground: "#000000",
                    borderRadius:        "12px",
                    fontFamily:         "var(--font-outfit), apple-system, sans-serif",
                    fontSize:           "14px",
                  },
                  elements: {
                    card: {
                      background:   "rgba(255,255,255,0.03)",
                      backdropFilter: "blur(24px)",
                      WebkitBackdropFilter: "blur(24px)",
                      border:       "1px solid rgba(255,255,255,0.08)",
                      boxShadow:    "0 0 0 1px rgba(255,255,255,0.04) inset, 0 32px 80px rgba(0,0,0,0.6)",
                      borderRadius: "18px",
                      padding:      "32px 28px",
                    },
                    headerTitle: {
                      color:      "rgba(255,255,255,0.92)",
                      fontSize:   "20px",
                      fontWeight: "600",
                      letterSpacing: "-0.4px",
                    },
                    headerSubtitle: {
                      color:    "rgba(255,255,255,0.35)",
                      fontSize: "13px",
                    },
                    socialButtonsIconButton: {
                      background:   "rgba(255,255,255,0.05)",
                      border:       "1px solid rgba(255,255,255,0.08)",
                      borderRadius: "10px",
                    },
                    dividerLine: {
                      background: "rgba(255,255,255,0.07)",
                    },
                    dividerText: {
                      color: "rgba(255,255,255,0.25)",
                    },
                    formFieldLabel: {
                      color:      "rgba(255,255,255,0.5)",
                      fontSize:   "12px",
                      fontWeight: "400",
                    },
                    formFieldInput: {
                      background:   "rgba(255,255,255,0.04)",
                      border:       "1px solid rgba(255,255,255,0.09)",
                      borderRadius: "10px",
                      color:        "rgba(255,255,255,0.88)",
                      fontSize:     "14px",
                    },
                    formButtonPrimary: {
                      background:   "#ffffff",
                      color:        "#000000",
                      borderRadius: "10px",
                      fontWeight:   "500",
                      fontSize:     "14px",
                      boxShadow:    "0 2px 16px rgba(255,255,255,0.12)",
                    },
                    footerActionLink: {
                      color: "rgba(255,255,255,0.6)",
                    },
                    identityPreviewText: {
                      color: "rgba(255,255,255,0.7)",
                    },
                    identityPreviewEditButton: {
                      color: "rgba(255,255,255,0.4)",
                    },
                  },
                }}
              />
            </SignedOut>
            <SignedIn>{children}</SignedIn>
          </main>
        </ClerkProvider>

        {/* ── Keyframe animations ───────────────────────── */}
        <style>{`
          @keyframes drift1 {
            0%, 100% { transform: translate(0, 0); }
            40%       { transform: translate(14px, -22px); }
            70%       { transform: translate(-8px, 10px); }
          }
          @keyframes drift2 {
            0%, 100% { transform: translate(0, 0); }
            50%       { transform: translate(-20px, -18px); }
          }
        `}</style>
      </body>
    </html>
  );
}